version: '3'
services:
  healthcheckr:
    image: jjrom/healthcheckr-client:latest
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 1m
      timeout: 5s